import vue from '@vitejs/plugin-vue';
import { defineConfig } from 'vite';
import { fileURLToPath, URL } from 'node:url';
import { resolve, join, relative } from 'path';
import VitePluginSvgSpritemap from '@spiriit/vite-plugin-svg-spritemap';
import { version } from './package.json';
import { readdirSync } from 'node:fs';
import tailwindcss from "@tailwindcss/vite";
import fs from 'node:fs';
import { basename } from 'node:path';


/**
 * Vite plugin that fixes the import of a virtual SVG spritemap generated by @spiriit/vite-plugin-svg-spritemap.
 *
 * In development mode, it provides a virtual empty module for `./__spritemap`
 * so that Vite doesn't throw an error due to the missing file.
 *
 * In build mode, it rewrites legacy import paths like './FIcon/assets/sprite.svg'
 * (left over from the source structure) to the final path './assets/sprite.svg',
 * which should match the one declared in package.json exports.
 *
 * Maybe wrong, but works.
 */
function FixFIconSpriteImport() {
	const RAW_ID = './__spritemap';
	const VIRTUAL_ID = '\0virtual:__spritemap';

	// Массив замен: [что заменить, на что заменить]
	const replacements = [
		['./assets/sprite.svg', '../assets/sprite.svg'],
		['FIcon/assets/sprite.svg', 'assets/sprite.svg'],
	];

	return {
		name: 'fix-sprite-import',

		resolveId(source) {
			if (source === RAW_ID) {
				return VIRTUAL_ID;
			}
			return null;
		},

		load(id) {
			if (id === VIRTUAL_ID) {
				return 'export default "";';
			}
			return null;
		},

		generateBundle(_, bundle) {
			for (const chunk of Object.values(bundle)) {
				if (chunk.type !== 'chunk') continue;

				let updated = chunk.code;

				for (const [from, to] of replacements) {
					if (updated.includes(from)) {
						updated = updated.replaceAll(from, to);
					}
				}

				if (updated !== chunk.code) {
					chunk.code = updated;
				}
			}
		},
	};
}


/**
 * Recursively scans a directory tree to discover Vue component entry points and constants modules.
 *
 * This function is typically used to build the `entry` option of Vite's library mode.
 * It walks through all subdirectories under the given `dir`, and for each directory:
 *
 * - If a file named `index.vue` is found, it is considered the main entry point of the component.
 * - If a file named `constants.js` is found, it is considered an auxiliary entry point (e.g., exporting named constants).
 *
 * For each matching file, the function adds an entry to the returned object where:
 *   - The key is the relative path from the `src` directory to the file, *without extension*.
 *   - The value is the absolute resolved path to the file.
 *
 * For example, if you have:
 *   src/FButton/index.vue
 *   src/FButton/constants.js
 *
 * The result will be:
 *   {
 *     "FButton/index": "/absolute/path/to/src/FButton/index.vue",
 *     "FButton/constants": "/absolute/path/to/src/FButton/constants.js"
 *   }
 *
 * @param {string} dir - The root directory to start scanning from.
 * @returns {Object<string, string>} An object mapping relative entry names to absolute file paths.
 */
function findVueEntries(dir) {
	const entries = {};

	const items = readdirSync(dir, { withFileTypes: true });
	for (const item of items) {
		const fullPath = join(dir, item.name);

		if (item.isDirectory()) {
			const sub = findVueEntries(fullPath);
			Object.assign(entries, sub);

		} else if (item.isFile() && item.name === 'index.vue') {
			const rel = relative('src', fullPath).replace(/\.vue$/, '');
			entries[rel] = resolve(fullPath);

		} else if (item.isFile() && item.name === 'constants.js') {
			const rel = relative('src', fullPath).replace(/\.js$/, '');
			entries[rel] = resolve(fullPath);

		} else if (item.isFile() && item.name === 'directive.js') {
			const rel = relative('src', fullPath).replace(/\.js$/, '');
			entries[rel] = resolve(fullPath);

		} else if (item.isFile() && item.name === 'utils.js') {
			const rel = relative('src', fullPath).replace(/\.js$/, '');
			entries[rel] = resolve(fullPath);
		}
	}

	return entries;
}


/**
 * Vite plugin that copies all `*.tailwind.css` files found under `src/` into the `dist/` directory,
 * preserving their relative paths.
 *
 * Scans `src/` recursively for files matching the `*.tailwind.css` pattern and, after the bundle
 * is written, copies each one to the corresponding path under `dist/`. The destination directory
 * is created automatically if it does not exist.
 *
 * For example:
 *   src/styles/theme.tailwind.css  →  dist/styles/theme.tailwind.css
 *   src/forms/FButton/style.tailwind.css  →  dist/forms/FButton/style.tailwind.css
 */
function copyTailwindPlugin() {
	const srcDir = resolve(__dirname, 'src');
	const distDir = resolve(__dirname, 'dist');

	function findTailwindFiles(dir) {
		const results = [];
		for (const item of readdirSync(dir, { withFileTypes: true })) {
			const fullPath = join(dir, item.name);
			if (item.isDirectory()) {
				results.push(...findTailwindFiles(fullPath));
			} else if (item.isFile() && item.name.endsWith('.tailwind.css')) {
				results.push(fullPath);
			}
		}
		return results;
	}

	return {
		name: 'copy-tailwind-css',

		writeBundle() {
			const files = findTailwindFiles(srcDir);

			for (const src of files) {
				const rel = relative(srcDir, src);
				const dest = join(distDir, rel);

				fs.mkdirSync(resolve(dest, '..'), { recursive: true });
				fs.copyFileSync(src, dest);

				const size = fs.statSync(dest).size / 1024;

				this.info(`${rel} → dist/${rel} ${size.toFixed(2)} kB`);
			}
		},
	};
}


export default defineConfig({
	base: process.env.BASE_URL || '/',
	plugins: [
		vue(),
		tailwindcss(),
		VitePluginSvgSpritemap(
			'./src/FIcon/icons/*.svg',
			{
				output: {
					name: 'sprite.svg',
					filename: 'sprite[extname]',
					use: false,
					view: false,
				},
				prefix: 'ficon-',
			},
		),
		FixFIconSpriteImport(),
		copyTailwindPlugin(),
	],
	define: {
		__VERSION__: JSON.stringify(version),
	},
	build: {
		cssTarget: ['chrome123', 'firefox120', 'safari17.5'],
		lib: {
			name: 'Futility UI',
			entry: {
				'index': resolve(__dirname, 'src/index.js'),
				...findVueEntries(resolve('src')),
				'forms/FInput/ClearButton': resolve(__dirname, 'src/forms/FInput/ClearButton.vue'),
				'forms/FInput/ShowPasswordButton': resolve(__dirname, 'src/forms/FInput/ShowPasswordButton.vue'),
				'forms/FGenericForm/useWidget': resolve(__dirname, 'src/forms/FGenericForm/useWidget.js'),
				'FModal/useFModal': resolve(__dirname, 'src/FModal/useFModal.js'),
				'forms/FGenericForm/widgets/FInputWidget': resolve(__dirname, 'src/forms/FGenericForm/widgets/FInputWidget.vue'),
				'styles/base.css': resolve(__dirname, 'src/styles/base.tailwind.css'),
				'styles/components.css': resolve(__dirname, 'src/styles/components.tailwind.css'),
			},
			fileName: (format, entryName) =>`${entryName}.${format}.js`,
			formats: [ 'es', 'cjs' ],
		},
		rollupOptions: {
			external: [
				'vue',
				'vue-final-modal',
				`.${process.env.BASE_URL || '/'}assets/sprite.svg`,
			],
			output: {
				globals: {
					vue: 'Vue',
				},
				assetFileNames: (assetInfo) => {
					const name = assetInfo.name
						?? assetInfo.names?.[0]
						?? assetInfo.originalFileNames?.[0]
						?? '';

					if (name.endsWith('.css')) {
						return '[name][extname]';
					}

					return 'assets/[name][extname]';
				},
			},
		},
		cssCodeSplit: true,
		treeShaking: true,
	},
	server: {
		fs: {
			allow: ['.storybook'],
		},
	},
	resolve: {
		extensions: [ '.mjs', '.js', '.mts', '.ts', '.jsx', '.tsx', '.json', '.vue', '.mdx' ],
		alias: {
			'@/.storybook': fileURLToPath(new URL('./.storybook', import.meta.url)),
			'@': fileURLToPath(new URL('./src', import.meta.url)),
		},
	},
});
